apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: result.devopsintheclouds.com
    http:
      paths:
        - pathType: "Prefix"
          path: "/"
          backend:
            service:
              name: result
              port:
                number: 80
  - host: vote.devopsintheclouds.com
    http:
      paths:
        - pathType: "Prefix"
          path: "/"
          backend:
            service:
              name: vote
              port:
                number: 80
